language: csharp

os:
 - linux
 - osx

dist: trusty
osx_image: xcode9.1

mono: none
dotnet: 2.0.0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ulimit -n 2048; fi

script:
 - dotnet restore
 - cd NeoSharp.Client.Test
 - dotnet test
 - cd ../NeoSharp.Core.Test
 - dotnet test
